# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170216_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.ManyToManyField(blank=True, null=True, related_name='q', to='orders.Quantity'),
        ),
    ]
