# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170216_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Order'),
        ),
    ]
