# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='/content/products')),
                ('talla', models.CharField(choices=[('CHICA', 'CHICA'), ('MEDIANA', 'MEDIANA'), ('GRANDE', 'GRANDE')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
