# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170125_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='products'),
        ),
    ]
