# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170125_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='talla',
            new_name='size',
        ),
    ]
