# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170201_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHICA', 'CHICA'), ('MEDIANA', 'MEDIANA'), ('GRANDE', 'GRANDE')], max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='size',
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
