# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170202_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.ManyToManyField(related_name='sizes', to='products.Size'),
        ),
    ]
