# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170202_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLANCO', 'BLANCO')], max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ManyToManyField(related_name='colors', to='products.Color'),
        ),
    ]
