# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170202_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
