# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170202_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='products.Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Image'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.ManyToManyField(related_name='sizes', to='products.Size'),
        ),
    ]
