# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170202_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexa',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
