# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagini',
        ),
    ]
