# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170207_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='images',
        ),
        migrations.AddField(
            model_name='imagini',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='products.Producto'),
        ),
    ]
